---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: mj-ubuntu14
      box_url: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/data_bag_key"
    run_list:
      - recipe[mj-mysql::server]
    attributes:
      mj-mysql:
        version: "5.5"
